### ISSUE TITLE
/path/to/mlir-hello/include/Hello/HelloOps.td:7:40: error: Variable not defined: 'Pure'

### ISSUE THREAD

**Issue by benroywillis** [Lewuathe/mlir-hello#32]
I'm running on Ubuntu 18.04.4 LTS (with Linux kernel 4.15.0-101-generix x86_64).

I'm using LLVM 14 and building it with the following configuration:
source ~/.unset ; $CMAKE ../llvm/ -G Ninja -DLLVM_ENABLE_PROJECTS="clang;polly;flang;mlir;lld;openmp" -DCMAKE_INSTALL_PREFIX=/mnt/heorot-10/Installs/LLVM14/release/ -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_RTTI=ON -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="Native;NVPTX;AMDGPU" -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_INSTALL_UTILS=ON
(the extra LLVM submodules are for other tasks I'm interested in)

Then I configure mlir-hello (the update-llvm-2023-08-24 branch) with the following command
$CMAKE ../ -G Ninja -DLLVM_DIR=/mnt/heorot-10/Installs/LLVM14/release/lib/cmake/llvm/ -DMLIR_DIR=/mnt/heorot-10/Installs/LLVM14/release/lib/cmake/mlir/
($CMAKE points to an install of cmake 3.22.3 in user space)

when calling ninja I get the following output:

[1/13] Building HelloOpsTypes.cpp.inc...
FAILED: include/Hello/HelloOpsTypes.cpp.inc /mnt/heorot-10/Builds/mlir-hello/build/include/Hello/HelloOpsTypes.cpp.inc 
cd /mnt/heorot-10/Builds/mlir-hello/build && /mnt/heorot-10/Installs/LLVM14/release/bin/mlir-tblgen -gen-typedef-defs -typedefs-dialect=hello -I /mnt/heorot-10/Builds/mlir-hello/include/Hello -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Builds/mlir-hello/include -I/mnt/heorot-10/Builds/mlir-hello/build/include -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello /mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td --write-if-changed -o include/Hello/HelloOpsTypes.cpp.inc -d include/Hello/HelloOpsTypes.cpp.inc.d
/mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td:7:40: error: Variable not defined: 'Pure'
def ConstantOp : Hello_Op<"constant", [Pure]> {
                                       ^
[2/13] Building HelloOpsDialect.h.inc...
FAILED: include/Hello/HelloOpsDialect.h.inc /mnt/heorot-10/Builds/mlir-hello/build/include/Hello/HelloOpsDialect.h.inc 
cd /mnt/heorot-10/Builds/mlir-hello/build && /mnt/heorot-10/Installs/LLVM14/release/bin/mlir-tblgen -gen-dialect-decls -dialect=hello -I /mnt/heorot-10/Builds/mlir-hello/include/Hello -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Builds/mlir-hello/include -I/mnt/heorot-10/Builds/mlir-hello/build/include -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello /mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td --write-if-changed -o include/Hello/HelloOpsDialect.h.inc -d include/Hello/HelloOpsDialect.h.inc.d
/mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td:7:40: error: Variable not defined: 'Pure'
def ConstantOp : Hello_Op<"constant", [Pure]> {
                                       ^
[3/13] Building HelloOps.h.inc...
FAILED: include/Hello/HelloOps.h.inc /mnt/heorot-10/Builds/mlir-hello/build/include/Hello/HelloOps.h.inc 
cd /mnt/heorot-10/Builds/mlir-hello/build && /mnt/heorot-10/Installs/LLVM14/release/bin/mlir-tblgen -gen-op-decls -I /mnt/heorot-10/Builds/mlir-hello/include/Hello -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Builds/mlir-hello/include -I/mnt/heorot-10/Builds/mlir-hello/build/include /mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td --write-if-changed -o include/Hello/HelloOps.h.inc -d include/Hello/HelloOps.h.inc.d
/mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td:7:40: error: Variable not defined: 'Pure'
def ConstantOp : Hello_Op<"constant", [Pure]> {
                                       ^
[4/13] Building HelloOps.cpp.inc...
FAILED: include/Hello/HelloOps.cpp.inc /mnt/heorot-10/Builds/mlir-hello/build/include/Hello/HelloOps.cpp.inc 
cd /mnt/heorot-10/Builds/mlir-hello/build && /mnt/heorot-10/Installs/LLVM14/release/bin/mlir-tblgen -gen-op-defs -I /mnt/heorot-10/Builds/mlir-hello/include/Hello -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Builds/mlir-hello/include -I/mnt/heorot-10/Builds/mlir-hello/build/include -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello /mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td --write-if-changed -o include/Hello/HelloOps.cpp.inc -d include/Hello/HelloOps.cpp.inc.d
/mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td:7:40: error: Variable not defined: 'Pure'
def ConstantOp : Hello_Op<"constant", [Pure]> {
                                       ^
[5/13] Building HelloOpsDialect.cpp.inc...
FAILED: include/Hello/HelloOpsDialect.cpp.inc /mnt/heorot-10/Builds/mlir-hello/build/include/Hello/HelloOpsDialect.cpp.inc 
cd /mnt/heorot-10/Builds/mlir-hello/build && /mnt/heorot-10/Installs/LLVM14/release/bin/mlir-tblgen -gen-dialect-defs -dialect=hello -I /mnt/heorot-10/Builds/mlir-hello/include/Hello -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Builds/mlir-hello/include -I/mnt/heorot-10/Builds/mlir-hello/build/include -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello /mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td --write-if-changed -o include/Hello/HelloOpsDialect.cpp.inc -d include/Hello/HelloOpsDialect.cpp.inc.d
/mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td:7:40: error: Variable not defined: 'Pure'
def ConstantOp : Hello_Op<"constant", [Pure]> {
                                       ^
[6/13] Building HelloOpsTypes.h.inc...
FAILED: include/Hello/HelloOpsTypes.h.inc /mnt/heorot-10/Builds/mlir-hello/build/include/Hello/HelloOpsTypes.h.inc 
cd /mnt/heorot-10/Builds/mlir-hello/build && /mnt/heorot-10/Installs/LLVM14/release/bin/mlir-tblgen -gen-typedef-decls -typedefs-dialect=hello -I /mnt/heorot-10/Builds/mlir-hello/include/Hello -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Installs/LLVM14/release/include -I/mnt/heorot-10/Builds/mlir-hello/include -I/mnt/heorot-10/Builds/mlir-hello/build/include -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello -I/mnt/heorot-10/Builds/mlir-hello/build/include/Hello /mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td --write-if-changed -o include/Hello/HelloOpsTypes.h.inc -d include/Hello/HelloOpsTypes.h.inc.d
/mnt/heorot-10/Builds/mlir-hello/include/Hello/HelloOps.td:7:40: error: Variable not defined: 'Pure'
def ConstantOp : Hello_Op<"constant", [Pure]> {
                                       ^
ninja: build stopped: subcommand failed.

**Comment by Lewuathe** [comment]
Thanks for the report. I think you are using the old LLVM repository. Could you try the latest main branch?

We have tested the version in the thirdparty directory at least.

https://github.com/Lewuathe/mlir-hello/tree/main/thirdparty/llvm-project

**Comment by benroywillis** [comment]
Thank you for the help, that fixed the issue
