### ISSUE TITLE
build error for project

### ISSUE THREAD

**Issue by AI-Marvel** [Lewuathe/mlir-hello#6]
I tried to use the sh script to build this project, but the following error appeared in the last step.

hello-opt/CMakeFiles/hello-opt.dir/hello-opt.cpp.o: In function `hello::HelloDialect::HelloDialect(mlir::MLIRContext*)':
hello-opt.cpp:(.text._ZN5hello12HelloDialectC2EPN4mlir11MLIRContextE[_ZN5hello12HelloDialectC5EPN4mlir11MLIRContextE]+0x5b): undefined reference to `vtable for hello::HelloDialect'
hello-opt/CMakeFiles/hello-opt.dir/hello-opt.cpp.o: In function `mlir::TypeID mlir::TypeID::get<hello::HelloDialect>()':
hello-opt.cpp:(.text._ZN4mlir6TypeID3getIN5hello12HelloDialectEEES0_v[_ZN4mlir6TypeID3getIN5hello12HelloDialectEEES0_v]+0x5): undefined reference to `mlir::TypeID mlir::detail::TypeIDExported::get<hello::HelloDialect>()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
bash: ./build/bin/hello-opt: No such file or directory
/root/dev2/mlir/llvm-project/build/bin/lli: Symbols not found: [ main ]

I don't know where the problem is, can you help me? 
Thank you very much.

**Comment by Lewuathe** [comment]
Sorry for the late response. Could you try again with the latest code?
